---
  - name: Check if rsync is installed
    apt:
      name: rsync
      state: present
    tags: [ never, backup ]

  - name: Synchronize Docker Volumes
    ansible.posix.synchronize:
      mode: pull
      src: /var/lib/docker/volumes
      dest: "{{ backup_path }}"
      rsync_opts:
        - "--exclude=backingFsBlockDev"
      delete: yes
    tags: [ never, backup ]

  - name: Synchronize Docker Configs in /opt/
    ansible.posix.synchronize:
      mode: pull
      src: /opt/docker_cfg
      dest: "{{ backup_path }}"
      delete: yes
    tags: [ never, backup ]

  - import_tasks: "{{ role_path }}/tasks/backup_vaultwarden.yml"
    tags: [ never, backup ]

    