---
    - name: Deploy Adguard
      become_user: dockeruser
      community.docker.docker_container:
        name: adguard
        image: adguard/adguardhome
        ports:
          - "53:53"
          - "53:53/udp"
          - "127.0.0.1:8081:80"
          - "853:853"
        volumes:
          - adguard_conf:/opt/adguardhome/conf
          - adguard_data:/opt/adguardhome/work
        restart_policy: unless-stopped
