---
- name: Create Compose Directory
  ansible.builtin.file:
    path: /opt/docker_cfg/compose
    state: directory
    owner: dockeruser
    group: dockeruser

- name: Copy Docker Compose files
  become_user: dockeruser
  copy:
    src: files/{{ item }}
    dest: /opt/docker_cfg/compose
  loop:
  - monitoring-compose.yml
  - teamspeak-compose.yml

- name: Deploy Docker Compose stack
  become_user: dockeruser
  docker_compose:
    project_src: /opt/docker_cfg/compose
    files:
    - monitoring-compose.yml
    - teamspeak-compose.yml