---
 - name: Create certbot_secrets Volume if it does not exist
   become_user: dockeruser
   docker_volume:
     name: certbot_secrets
     state: present

 - name: Creating Cloudflare Credentials File
   copy:
     dest: "/var/lib/docker/volumes/certbot_secrets/_data/cloudflare.ini"
     content: |
       dns_cloudflare_api_token = {{cloudflare_api_token}}

 - name: Set Permissions for the Credentials File
   ansible.builtin.file:
     path: /var/lib/docker/volumes/certbot_secrets/_data/cloudflare.ini
     owner: root
     group: root
     mode: '0600'

 - name: Get Checksum pre Cert Renewal
   stat:
     path: /var/lib/docker/volumes/letsencrypt/_data/live
     checksum_algorithm: sha256
     get_checksum: yes
   register: chksm

 - name: Print Checksum
   ansible.builtin.debug:
     var: chksm
