---
 - name: Create certbot_secrets Volume if it does not exist
   become_user: dockeruser
   docker_volume:
     name: certbot_secrets
     state: present

 - name: Creating Cloudflare Credentials File
   copy:
     dest: "/var/lib/docker/volumes/certbot_secrets/_data/cloudflare.ini"
     content: |
       dns_cloudflare_api_token = {{cloudflare_api_token}}

 - name: Set Permissions for the Credentials File
   ansible.builtin.file:
     path: /var/lib/docker/volumes/certbot_secrets/_data/cloudflare.ini
     owner: root
     group: root
     mode: '0600'

 - name: Get Checksum pre Cert Renewal
   stat:
     path: /var/lib/docker/volumes/letsencrypt/_data/live
     checksum_algorithm: sha256
     get_checksum: yes
   register: chksm

 - name: Print Checksum
   ansible.builtin.debug:
     var: chksm.stat.checksum
     verbosity: 4

 - name: Attempt SSL certificate retrieval
   become_user: dockeruser
   shell: >-
     docker run
     --rm
     --name=certbot
     -v letsencrypt:/etc/letsencrypt
     -v certbot_secrets:/.secrets
     certbot/dns-cloudflare
     certonly
     --non-interactive
     {% if lets_encrypt_staging %}--test-cert{% endif %}
     --dns-cloudflare
     --dns-cloudflare-credentials /.secrets/cloudflare.ini
     --agree-tos
     --email={{ lets_encrypt_email }}
     -d {{ domain_name }}
   register: result_certbot
