---
  - name: Install UFW
    apt:
      name: ufw
      state: present
  
  - name: UFW - Allow OpenSSH
    community.general.ufw:
      rule: allow
      name: OpenSSH
      src: '10.0.0.0/8'

  - name: Enable UFW and Deny Default
    community.general.ufw:
      state: enabled
      policy: deny