---
  - import_tasks: "{{ role_path }}/tasks/install_docker.yml"
    tags:
      - never
      - setup
  - import_tasks: "{{ role_path }}/tasks/install_ufw.yml"
    tags:
      - never
      - setup
  - import_tasks: "{{ role_path }}/tasks/push_volumes.yml"
    tags:
      - never
      - restore
  - import_tasks: "{{ role_path }}/tasks/unattended_upgrades.yml"
    tags:
      - never
      - setup