---
  - include_tasks: install_docker.yml
    tags:
      - setup
      - restore
  - include_tasks: install_ufw.yml
    tags:
      - setup
      - restore
  - include_tasks: push_volumes.yml
    tags:
      - restore